export const allContinents = {
  ALL_AMERICAS_COUNTRIES: 56,
  ALL_EUROPE_COUNTRIES: 53,
  ALL_AFRICA_COUNTRIES: 59,
  ALL_ASIA_COUNTRIES: 50,
  ALL_OCEANIA_COUNTRIES: 27,
  ALL_WORLD_COUNTRIES: 245,
};
